name: ChatProtectionPlus
main: net.willhastings.ChatProtectionPlus.ChatProtectionPlus
version: 1.0.1
softdepend: [Vault]
author: bill1993

commands:
  cpp:
    description: ChatProtection+ Command, and Sub Commands
    
permissions:
  cpp.admin:
    description: Access to /CPP command
  cpp.admin.*:
    description: Access to /CPP command, and all sub-commands
  cpp.admin.reload:
    description: Access to /CPP RELOAD sub-command
  cpp.admin.chat:
    description: Access to /CPP CHAT sub-command
  cpp.ignore.*:
    description: Will make ChatProtection+ ignore the user on all flags
  cpp.ignore.chat.lock:
    description: Will let the user bypass the chat lock
  cpp.ignore.chat.spam:
    description: Will let the user bypass the anti-spam feature
  cpp.ignore.anticaps:
    description: Will let the user bypass the maximum capital letters feature
  cpp.ignore.command.spam:
    description: Will let the user bypass the command-spam feature