name: ChatProtection+
main: net.willhastings.ChatProtectionPlus.ChatProtectionPlus
version: 2.0.0
softdepend: [Vault]
author: [bill1993, DUFC_Liam]



commands:
  cpp:
    description: ChatProtection+ protect your server against spamming and much more!
    
permissions:
  cpp.admin:
    description: Access to the command /CPP
  cpp.admin.*:
    description: Access to all /CPP commands, and all sub-commands
  cpp.admin.reload:
    description: Access to /CPP RELOAD
  cpp.admin.chat:
    description: Access to /CPP CHAT
  cpp.ignore.*:
    description: Will make ChatProtection+ ignore the user on all flags
  cpp.ignore.chat.lock:
    description: Will let the user bypass the chat lock
  cpp.ignore.chat.spam:
    description: Will let the user bypass the anti-spam feature
  cpp.ignore.anticaps:
    description: Will let the user bypass the maximum capital letters feature
  cpp.ignore.command.spam:
    description: Will let the user bypass the command-spam feature
